name: data_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  provider: ^6.1.2
  file_picker: ^4.3.2
  http: ^0.13.3
  get: ^4.6.6
  firebase_auth: ^5.1.4
  excel: ^4.0.3
  permission_handler: ^11.3.1
  weather: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

